fusion_connector.settings:
  type: config_object
  label: Fusion Connector Settings
  mapping:
    disabled_fields:
      type: sequence
      label: Fields that will not be exposed
      sequence:
        type: sequence
        sequence:
          type: string

    disabled_entity_type_languages:
      type: sequence
      label: Disable language per entity
      sequence:
        type: sequence
        sequence:
          type: string

    disabled_languages:
      type: sequence
      label: Languages that will not be exposed
      sequence:
        - type: string

    disabled_entities:
      type: sequence
      label: Entities that will not be exposed
      sequence:
        - type: string
